export const UPDATE_MOVIE_TITLES_FROM_SEARCH = 'UPDATE_MOVIE_TITLES_FROM_SEARCH';
export const UPDATE_DROPDOWN_STATE = 'UPDATE_DROPDOWN_STATE';
export const UPDATE_SELECTED_MOVIE_LIST = 'UPDATE_SELECTED_MOVIE_LIST';
export const UPDATE_ERROR_MESSAGE = 'UPDATE_ERROR_MESSAGE'